### ISSUE TITLE
Add ability to upload media

### ISSUE THREAD

**Issue by tehcodedninja** [endroid/Twitter#16]
Add function to upload media or change header's content type for the ability.

**Comment by Headd2k** [comment]
i was also missing this feature but was able to extend the base endroid twitter class with my own "upload media" method. maybe this might be a "quick fix" for anyone missing this feature too. i created a gist showing my method:

https://gist.github.com/Headd2k/af60cbeee258583ac5b4f8ec687554de

i would be happy to provide a pr with this feature integrated into the endroid base twitter class, but i'm currently not sure how to handle the new base url (upload instead of api) in this context.

**Comment by endroid** [comment]
Hi @Headd2k I can update the class for you next week so it is not necessary to create a PR. Thank you for sharing your solution!

**Comment by umahanov** [comment]
@endroid 

Any update?

**Comment by endroid** [comment]
Added in 1.3.4
